### ISSUE TITLE
Provide installation info, Zend error

### ISSUE THREAD

**Issue by nekromoff** [das-lastenrad/software#1]
Please, provide clear installation info. After installing, I get:

```
Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: Invalid save_path provided; not a directory in /var/www/html/downloads/software/src/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php:229 Stack trace: #0 /var/www/html/downloads/software/src/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php(158): Zend\Session\Config\StandardConfig->setSavePath(false) #1 /var/www/html/downloads/software/src/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath(false) #2 /var/www/html/downloads/software/src/module/Application/Module.php(69): Zend\Session\Config\StandardConfig->setOptions(Array) #3 [internal function]: Application\Module->onBootstrap(Object(Zend\Mvc\MvcEvent)) #4 /var/www/html/downloads/software/src/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #5 /var/www/html/downloads/softwar in /var/www/html/downloads/software/src/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php on line 229
```

**Comment by nekromoff** [comment]
These lines should help with installation:

1. Create /data/session directory in /software/src/ and make it writable
2. Add the following lines to /software/src/config/autload/global.php:
```
  'db' => array(
      'driver'         => 'Pdo',
      'dsn'            => 'mysql:dbname=lastenrad;host=localhost',
   ),
   'service_manager' => array(
      'factories' => array(
         'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
      ),
   ),
```
to make it look like this:
```
return array(
	'email_receiver' => 'email@example.com',
	'email_sender' => 'email@example.com',
    'db' => array(
      'driver'         => 'Pdo',
      'dsn'            => 'mysql:dbname=lastenrad;host=localhost',
   ),
   'service_manager' => array(
      'factories' => array(
         'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
      ),
   ),
);
```

Reload in browser:
http://yourhost/software/src/public/
